; PlatformIO Project Configuration for ESP32-C3 Bore Example
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino

; Include library from parent directory
lib_extra_dirs = ../../lib

; Serial monitor options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build options
build_type = debug
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

; Upload options
upload_speed = 921600

; Library dependencies
lib_deps =
    bblanchon/ArduinoJson@^7.0.0

; Extra scripts (optional)
; extra_scripts = pre:rename.py
